const fs=require('node:fs'),assert=require('node:assert/strict');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
let cleanup=async()=>{};
(async()=>{
  const browser=await (await fetch('http://127.0.0.1:9224/json/version')).json();
  const browserWs=new WebSocket(browser.webSocketDebuggerUrl);await new Promise(r=>browserWs.addEventListener('open',r,{once:true}));
  let browserId=0;const browserPending=new Map();
  browserWs.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=browserPending.get(m.id);browserPending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}});
  const browserSend=(method,params={})=>new Promise((resolve,reject)=>{const id=++browserId;browserPending.set(id,{resolve,reject});browserWs.send(JSON.stringify({id,method,params}));});
  const {browserContextId}=await browserSend('Target.createBrowserContext');
  cleanup=async()=>{await browserSend('Target.disposeBrowserContext',{browserContextId});browserWs.close();};
  const {targetId}=await browserSend('Target.createTarget',{url:'about:blank',browserContextId});
  const target=(await (await fetch('http://127.0.0.1:9224/json/list')).json()).find(target=>target.id===targetId);
  const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
  let id=0;const pending=new Map(),errors=[];
  const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});ws.send(JSON.stringify({id:key,method,params}));});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method!=='Fetch.requestPaused')return;const {requestId,request}=m.params;const file=request.url.includes('confetti.browser.min.js')?'dailyos-confetti.min.js':request.url.includes('react-dom.production')?'dailyos-react-dom.min.js':request.url.includes('react.production')?'dailyos-react.min.js':request.url.includes('babel.min.js')?'dailyos-babel-7.29.6.min.js':null;if(file)send('Fetch.fulfillRequest',{requestId,responseCode:200,responseHeaders:[{name:'Content-Type',value:'application/javascript'},{name:'Access-Control-Allow-Origin',value:'*'}],body:fs.readFileSync('/private/tmp/'+file).toString('base64')});else send('Fetch.continueRequest',{requestId});});
  await send('Fetch.enable',{patterns:[{urlPattern:'*cdnjs.cloudflare.com*',requestStage:'Request'},{urlPattern:'*cdn.jsdelivr.net*',requestStage:'Request'}]});
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.clear();localStorage.setItem('dos_backup_meta_v1',JSON.stringify({lastBackup:Date.now()}));localStorage.setItem('dos_habits_v1',JSON.stringify([{id:'read',name:'Read',emoji:'📖',startTime:'09:00',endTime:'09:30'},{id:'run',name:'Run',emoji:'🏃'}]));window._cspEvents=[];document.addEventListener('securitypolicyviolation',e=>window._cspEvents.push(e.violatedDirective+':'+e.blockedURI));`});
  await send('Page.navigate',{url:'http://127.0.0.1:8765/index.html'});
  for(let i=0;i<40;i++){if(await evaluate(`!!document.querySelector('input[type="email"]')`))break;await wait(250);}
  assert(await evaluate(`!!document.querySelector('input[type="email"]')`),'Signed-out visitor sees sign-in');
  assert(!await evaluate(`!!document.querySelector('.app-nav,.xp-panel,.habit-list,.progress-grid')`),'Signed-out visitor sees no personal content');
  assert(!await evaluate(`document.body.textContent.includes('Create account')`),'Public signup is absent');
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`(()=>{let sync;const listeners=new Set();let status={configured:true,connected:true,message:'Synced',pending:0,email:'test@example.test'};Object.defineProperty(window,'DailySync',{configurable:true,get:()=>sync,set:value=>{sync=value;sync.status=()=>({...status});sync.subscribe=fn=>{listeners.add(fn);fn({...status});return()=>listeners.delete(fn);};window._setTestSyncStatus=(connected,checkingSession=false)=>{status={...status,connected,checkingSession,message:checkingSession?'Checking session…':connected?'Synced':'Signed out'};listeners.forEach(fn=>fn({...status}));};}});})();`});
  await send('Page.navigate',{url:'http://127.0.0.1:8765/index.html'});
  for(let i=0;i<40;i++){if(await evaluate(`!!document.querySelector('.xp-panel')`))break;await wait(250);}
  assert(await evaluate(`!!document.querySelector('.xp-panel')`),'Signed-in app renders without requiring an AI key: '+errors.join('\n'));
  await evaluate(`window._setTestSyncStatus(false,true)`);await wait(100);assert(await evaluate(`!!document.querySelector('[aria-label="Checking saved session"]')`),'Session check shows matching splash');assert(!await evaluate(`!!document.querySelector('input[type="email"]')`),'Session check never flashes login');await evaluate(`window._setTestSyncStatus(true)`);await wait(100);
  const click=async expression=>{await evaluate(`(${expression}).click()`);await wait(150);};
  const button=label=>`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)})`;
  const tab=label=>click(`[...document.querySelectorAll('.app-nav button')].find(b=>b.textContent.trim()===${JSON.stringify(label)})`);
  const input=async(label,value)=>{await evaluate(`(()=>{const e=document.querySelector('input[aria-label=${JSON.stringify(label)}]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait(60);};
  await tab('Habits');
  const today=await evaluate('tdk()');
  const edit=async(start,end)=>{await click(`document.querySelector('button[aria-label="Edit time for Read"]')`);await input('Habit start time',start);await input('Habit end time',end);await click(button('Save habit'));};
  await edit('10:00','10:30');assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/10:00 AM/);
  await edit('11:00','11:30');assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/11:00 AM/);
  assert.equal(await evaluate(`ld('dos_habits_v1',[])[0].startTime`),'09:00','Day edit leaves base time alone');
  assert.equal(await evaluate(`ld('dos_planner_v1',{})[tdk()].habitTimes.read.start`),'11:00');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.habit-list>div')).transform`),'none','Resting row has no compositor transform');
  const nextDay=async()=>{const label=await evaluate(`new Date(shiftDateKey(tdk(),1)+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})`);if(!await evaluate(`!!document.querySelector('button[aria-label=${JSON.stringify(label)}]')`))await click(`document.querySelector('button[aria-label="Next week"]')`);await click(`document.querySelector('button[aria-label=${JSON.stringify(label)}]')`);};
  await nextDay();assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/9:00 AM/);
  await click(button('Today'));await click(`document.querySelector('button[aria-label="Edit habit Read"]')`);await input('Habit start time','12:00');await input('Habit end time','12:30');await click(`document.querySelector('input[aria-label="Apply time to all days"]')`);await click(button('Save habit'));assert.equal(await evaluate(`ld('dos_habits_v1',[])[0].startTime`),'12:00');assert(!await evaluate(`ld('dos_planner_v1',{})[tdk()].habitTimes.read`));
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);
  await click(`document.querySelector('button[aria-label="Remove Read"]')`);assert(await evaluate(`!!document.querySelector('[role="dialog"]')`));await click(button('Cancel'));assert(await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));
  await click(`document.querySelector('button[aria-label="Remove Read"]')`);await click(button('Delete for today only'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await nextDay();assert(await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));await click(`document.querySelector('button[aria-label="Remove Read"]')`);await click(button('Delete from today onward'));assert.equal(await evaluate(`ld('dos_habits_v1',[]).find(h=>h.id==='read').endDate`),await evaluate(`shiftDateKey(tdk(),1)`));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));await click(button('Today'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));
  await click(`document.querySelector('button[aria-label="Add urgent reminder"]')`);await input('Urgent reminder text','Check appointment');await click(button('Save reminder'));await click(`document.querySelector('button[aria-label="Complete urgent reminder Check appointment"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),25);assert.equal(await evaluate(`document.querySelector('button[aria-label="Complete urgent reminder Check appointment"]').getAttribute('aria-checked')`),'true');await click(`document.querySelector('button[aria-label="Complete urgent reminder Check appointment"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await click(button('+ Add habit'));await input('Habit text','Forward only');await click(button('Every day'));await click(button('Save habit'));assert.equal(await evaluate(`ld('dos_habits_v1',[]).find(h=>h.name==='Forward only').startDate`),today);await click(`document.querySelector('button[aria-label="Mark Forward only"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);await nextDay();await click(`document.querySelector('button[aria-label="Remove Forward only"]')`);await click(button('Delete from today onward'));assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);await click(button('Today'));assert(await evaluate(`!!document.querySelector('button[aria-label="Mark Forward only"]')`));await click(`document.querySelector('button[aria-label="Mark Forward only"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);await click(`document.querySelector('button[aria-label="Remove Forward only"]')`);await click(button('Delete for today only'));
  await tab('Home');await click(`document.querySelector('button[aria-label="Bottle 1"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),5);await click(`document.querySelector('button[aria-label="Bottle 1"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await click(`document.querySelector('button[aria-label="Account and sync settings"]')`);assert(await evaluate(`document.querySelector('[role="dialog"]').textContent.includes('Sign out')`));await click(`document.querySelector('[role="dialog"] button')`);
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await wait(250);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.app-nav')).width`),'220px');assert.equal(await evaluate(`getComputedStyle(document.querySelector('.home-layout')).display`),'grid');
  assert(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),'Desktop has no horizontal overflow');
  for(const name of ['Health','Habits','Stack','Progress','Home']){await tab(name);assert(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),name+' has no desktop overflow');}
  await tab('Habits');await evaluate(`(()=>{const b=document.querySelector('button[aria-label="Reorder Run"]');b.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));})()`);
  await click(button('+ Add habit'));await input('Habit text','Stretch');await click(button('Save habit'));
  await evaluate(`document.querySelector('button[aria-label="Reorder Run"]').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))`);await wait(150);
  assert.equal(await evaluate(`document.querySelector('.habit-list button[aria-label^="Mark "]').getAttribute('aria-label')`),'Mark Stretch','Keyboard reorder moves the item');
  const points=await evaluate(`(()=>{const a=document.querySelector('button[aria-label="Reorder Run"]').getBoundingClientRect(),b=document.querySelector('button[aria-label="Reorder Stretch"]').getBoundingClientRect();return {x:a.x+a.width/2,y:a.y+a.height/2,target:b.y};})()`);
  await send('Input.dispatchMouseEvent',{type:'mousePressed',x:points.x,y:points.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:points.x,y:points.target,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:points.x,y:points.target,button:'left',clickCount:1});await wait(450);
  assert.equal(await evaluate(`document.querySelector('.habit-list button[aria-label^="Mark "]').getAttribute('aria-label')`),'Mark Run','Mouse drag reorder moves the item');
  await click(`document.querySelector('button[aria-label="Remove Stretch"]')`);await click(button('Delete for today only'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Stretch"]')`),'Local habit deletes for today');
  await tab('Stack');const supplement=await evaluate(`document.querySelector('button[aria-label^="Mark "]').getAttribute('aria-label')`);await click(`document.querySelector('button[aria-label=${JSON.stringify(supplement)}]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),10);
  await tab('Health');await click(`[...document.querySelectorAll('[aria-label="Day activity"] button')].find(b=>b.textContent==='Gym')`);await click(button('Mark Gym'));assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),50);
  await tab('Home');const homeShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/private/tmp/dailyos-home-sync.png',Buffer.from(homeShot.data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await wait(250);
  const photoDates=await evaluate(`(async()=>{for(const record of await idbGetAll())await idbDel(record.date,true);const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1080;const ctx=canvas.getContext('2d');const gradient=ctx.createLinearGradient(0,0,720,1080);gradient.addColorStop(0,'#b39dfa');gradient.addColorStop(1,'#60a5fa');ctx.fillStyle=gradient;ctx.fillRect(0,0,720,1080);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9)),dates=[];for(let i=0;i<6;i++){const date=shiftDateKey(tdk(),i-5);dates.push(date);await idbPut({date,ts:1000+i,blob},true);}window._photoReads=[];const get=IDBObjectStore.prototype.get;IDBObjectStore.prototype.get=function(key){if(this.name==='bodyPhotos')window._photoReads.push(key);return get.call(this,key);};return dates;})()`);
  const photoHashes=await evaluate(`(async()=>Promise.all((await idbGetAll()).map(async photo=>[photo.date,Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await photo.blob.arrayBuffer()))).join(',')])))()`);
  await tab('Progress');
  for(let i=0;i<40;i++){if(await evaluate(`document.querySelectorAll('.progress-grid button').length===6`))break;await wait(100);}
  assert.equal(await evaluate(`document.querySelectorAll('.progress-grid button').length`),6,'All fixture photos appear');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.progress-grid')).gridTemplateColumns.split(' ').length`),4,'Laptop photo grid uses four columns');
  assert(await evaluate(`[...document.querySelectorAll('.progress-grid img')].every(img=>img.loading==='lazy'&&getComputedStyle(img).objectFit==='contain')`),'Grid uses lazy uncropped thumbnails');
  assert(await evaluate(`[...document.querySelectorAll('.progress-grid button')].every(button=>button.querySelector('span').textContent.trim().length>0&&Math.abs(button.getBoundingClientRect().width/button.getBoundingClientRect().height-.8)<.02)`),'Dates and consistent photo aspect ratio');
  assert.deepEqual((await evaluate(`window._photoReads`)).sort(),[photoDates[0],photoDates[5]].sort(),'Only comparison loads originals; grid uses thumbnails');
  for(let i=0;i<30;i++){if(await evaluate(`[...document.querySelectorAll('[aria-label="Before and after photo comparison"] img')].every(image=>image.dataset.originalLoaded==='true'&&image.naturalWidth===720)`))break;await wait(80);}
  assert(await evaluate(`[...document.querySelectorAll('[aria-label="Before and after photo comparison"] img')].every(image=>image.dataset.originalLoaded==='true'&&image.naturalWidth===720)`),'Both comparison images load original resolution');
  const captureChecks=await evaluate(`(async()=>{const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=2400;canvas.getContext('2d').fillRect(0,0,1600,2400);const jpeg=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.95)),png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const preserved=await fileToProgressBlob(jpeg),converted=await fileToProgressBlob(png),bitmap=await createImageBitmap(converted);let rejected=false;try{await fileToProgressBlob(new Blob([new Uint8Array(10*1024*1024+1)],{type:'image/jpeg'}));}catch{rejected=true;}return {exact:preserved===jpeg,width:bitmap.width,height:bitmap.height,rejected};})()`);
  assert.deepEqual(captureChecks,{exact:true,width:1600,height:2400,rejected:true},'JPEG bytes preserved, conversion retains full dimensions, oversized originals rejected without resizing');
  const thumbnail=await evaluate(`(async()=>{const photo=(await idbGetAll())[0];const cached=await DailyPhotos.thumbnail(photo,()=>{throw Error('Existing thumbnail should be reused');});const image=await createImageBitmap(cached);return {width:image.width,height:image.height,bytes:cached.size,original:photo.blob.size};})()`);
  assert.equal(thumbnail.height,360,'Thumbnail longest side is 360px');assert(thumbnail.width<720&&thumbnail.bytes<thumbnail.original,'Thumbnail is smaller than original');
  await click(`document.querySelectorAll('.progress-grid button')[2]`);
  const loaded=async()=>{for(let i=0;i<30;i++){if(await evaluate(`document.querySelector('.photo-dialog img')?.dataset.originalLoaded==='true'&&document.querySelector('.photo-dialog img').naturalWidth===720`))return;await wait(80);}throw Error('Full photo failed to load');};
  await loaded();
  assert.equal(await evaluate(`document.querySelector('.photo-dialog img').naturalWidth`),720,'Viewer uses retained full-size photo');
  const photoBounds=await evaluate(`(()=>{const image=document.querySelector('.photo-dialog img'),r=image.getBoundingClientRect();return {fits:r.top>=-1&&r.left>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1&&getComputedStyle(image).objectFit==='contain',rect:r.toJSON(),viewport:[innerWidth,innerHeight]};})()`);
  assert(photoBounds.fits,'Full photo fits laptop viewport: '+JSON.stringify(photoBounds));
  assert(await evaluate(`document.querySelector('.photo-dialog').textContent.includes(new Date(${JSON.stringify(photoDates[3])}+'T00:00').toLocaleDateString('en-US',{weekday:'short',month:'long',day:'numeric',year:'numeric'}))`),'Viewer shows full photo date');
  await click(`document.querySelector('.photo-dialog button[aria-label="Next"]')`);await loaded();assert.equal(await evaluate(`document.querySelector('.photo-dialog img').alt`),'Progress '+photoDates[4]);
  await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft'}))`);await loaded();assert.equal(await evaluate(`document.querySelector('.photo-dialog img').alt`),'Progress '+photoDates[3]);
  await click(`document.querySelector('.photo-dialog button[aria-label="Previous"]')`);await loaded();assert.equal(await evaluate(`document.querySelector('.photo-dialog img').alt`),'Progress '+photoDates[2]);
  await evaluate(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}))`);await wait(100);assert(!await evaluate(`!!document.querySelector('.photo-dialog')`),'Escape closes viewer');
  await click(`document.querySelector('.progress-grid button')`);await loaded();await click(`document.querySelector('[data-photo-backdrop]')`);assert(!await evaluate(`!!document.querySelector('.photo-dialog')`),'Click outside closes viewer');
  await click(`document.querySelector('.progress-grid button')`);await loaded();await click(`document.querySelector('.photo-dialog button[aria-label="Close"]')`);assert(!await evaluate(`!!document.querySelector('.photo-dialog')`),'Close button closes viewer');
  assert.deepEqual(await evaluate(`(async()=>Promise.all((await idbGetAll()).map(async photo=>[photo.date,Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await photo.blob.arrayBuffer()))).join(',')])))()`),photoHashes,'Thumbnail generation, slider and viewer preserve original bytes');
  assert(await evaluate(`!!document.querySelector('[aria-label="Before and after photo comparison"]')`),'Comparison feature retained');
  for(const [width,height,columns] of [[390,844,2],[800,900,3],[1600,1000,5]]){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width===390});await wait(180);assert.equal(await evaluate(`getComputedStyle(document.querySelector('.progress-grid')).gridTemplateColumns.split(' ').length`),columns,'Responsive columns at '+width);await click(`document.querySelector('.progress-grid button')`);await loaded();assert(await evaluate(`(()=>{const r=document.querySelector('.photo-dialog').getBoundingClientRect();return r.top>=0&&r.left>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;})()`),'Viewer fits viewport at '+width);await click(`document.querySelector('.photo-dialog button[aria-label="Close"]')`);}
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await tab('Home');
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert(await evaluate(`parseFloat(getComputedStyle(document.querySelector('.xp-fill')).transitionDuration)<.001`),'Reduced motion disables XP animation');
  const richThemeKeys=['modern','pokemon','akatsuki','vintage','zen','lagoon','dunes','observatory'],themeFonts=new Set(),themeMaterials=new Set();
  await click(`document.querySelector('button[aria-label="Change accent theme"]')`);
  assert.equal(await evaluate(`document.querySelectorAll('.theme-preview[data-preview="rich"]').length`),8,'Eight rich live preview thumbnails');
  assert.equal(await evaluate(`document.querySelectorAll('.theme-preview').length`),20,'All twenty themes remain available');
  const allThemeKeys=await evaluate(`Object.keys(THEMES)`);
  await evaluate(`window._themeWrites=[];window._themeWriteOriginal=DailySync.write;DailySync.write=(key,value)=>{if(key==='dos_theme_v1')window._themeWrites.push(value);return window._themeWriteOriginal(key,value);};`);
  for(const key of richThemeKeys){
    await click(`document.querySelector('.theme-picker-grid button:has([data-theme="${key}"])')`);
    assert.equal(await evaluate(`document.documentElement.dataset.theme`),key,'Live selection updates '+key);
    assert.equal(await evaluate(`ld('dos_theme_v1','')`),key,'Selection persists '+key);
    assert.equal(await evaluate(`window._themeWrites.at(-1)`),key,'Selection queues synchronization '+key);
    assert(await evaluate(`!!document.querySelector('.theme-sheet')`),'Live preview leaves picker open');
    const themeCheck=await evaluate(`(()=>{const s=getComputedStyle(document.documentElement),v=k=>s.getPropertyValue(k).trim();const lum=c=>{const a=c.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722;};const ratio=(a,b)=>{const l=[lum(a),lum(b)].sort((a,b)=>a-b);return(l[1]+.05)/(l[0]+.05);};const ink=['--ink','--ink-2','--ink-3'],accents=['--c-primary','--c-2','--c-3','--c-good','--c-action','--c-bad'];const motion=document.querySelector('.theme-motion'),motif=motion?.querySelector('.theme-motif'),preview=document.querySelector('.theme-preview[data-theme="${key}"] .preview-symbol');const duration=e=>e&&getComputedStyle(e).display!=='none'?parseFloat(getComputedStyle(e).animationDuration)||0:0;return {font:v('--font-body')+' / '+v('--font-display'),material:v('--material'),text:Math.min(...ink.flatMap(a=>['--bg','--bg-1'].map(b=>ratio(v(a),v(b))))),accent:Math.min(...accents.map(a=>ratio(v(a),v('--bg-1')))),button:Math.min(...accents.filter(a=>a!=='--c-bad').map(a=>ratio(v('--on-accent'),v(a)))),motion:duration(motif),previewMotion:duration(preview),motif:motion?.dataset.motif||null,motionVisible:!!motion&&getComputedStyle(motion).display!=='none'};})()`);
    assert(themeCheck.text>=4.5&&themeCheck.accent>=4.5&&themeCheck.button>=4.5,key+' normal text and accent contrast');
    assert(themeCheck.motion<.001&&themeCheck.previewMotion<.001,key+' respects reduced motion');
    if(['modern','pokemon','akatsuki'].includes(key))assert(!themeCheck.motionVisible,key+' uses lightweight page styling instead of animated SVG clones');
    if(key==='modern'){assert.equal(themeCheck.material,'none','Modern has no grid or texture gradient');assert.match(themeCheck.font,/Manrope.*Cormorant Garamond/,'Modern luxury font pairing');}
    else if(!['pokemon','akatsuki'].includes(key))assert.equal(themeCheck.motif,key,key+' has its own ambient motif');
    if(key==='pokemon')assert.match(themeCheck.font,/Nunito/,'Pokémon uses its playful legible font');
    if(key==='akatsuki')assert.match(themeCheck.font,/Manrope.*Permanent Marker/,'Akatsuki ink heading and readable body pairing');
    themeFonts.add(themeCheck.font);themeMaterials.add(themeCheck.material);
  }
  assert.equal(themeFonts.size,8,'Eight distinct font pairings');assert.equal(themeMaterials.size,6,'Six surface materials plus independent section motifs');
  await click(button('Done'));
  for(const [width,height] of [[390,844],[1440,1000]]){
    await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:width===390?3:1,mobile:width===390});
    for(const key of allThemeKeys){
      await tab('Home');await click(`document.querySelector('button[aria-label="Change accent theme"]')`);await click(`document.querySelector('.theme-picker-grid button:has([data-theme="${key}"])')`);
      assert.equal(await evaluate(`getComputedStyle(document.querySelector('.theme-picker-grid')).gridTemplateColumns.split(' ').length`),width===390?2:3,'Picker columns at '+width);
      assert(await evaluate(`document.querySelector('.theme-sheet').getBoundingClientRect().right<=innerWidth+1`),key+' picker fits '+width);await click(button('Done'));
      if(['modern','pokemon'].includes(key)){await click(`document.querySelector('button[aria-label="Change accent theme"]')`);assert.equal(await evaluate(`getComputedStyle(document.querySelector('.theme-backdrop')).backgroundColor`),'rgba(0, 0, 0, 0)',key+' live page remains visible behind picker');if(key==='pokemon')assert(await evaluate(`document.querySelector('.theme-preview[data-theme="pokemon"] .preview-pokeball').src.endsWith('/assets/themes/pokeball.svg')`),'Pokémon preview uses an actual Poké Ball');await click(button('Done'));}
      const themeShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/private/tmp/dailyos-'+key+'-'+width+'.png',Buffer.from(themeShot.data,'base64'));
      assert.equal(await evaluate(`ld('dos_theme_v1','')`),key,'Theme persists at '+width);
      if(['modern','pokemon','akatsuki'].includes(key))assert(await evaluate(`[...document.querySelectorAll('.app-nav>div>div[aria-hidden]')].every(element=>getComputedStyle(element).display==='none')`),key+' opaque highlight does not cover navigation labels');
      for(const name of ['Home','Health','Habits','Stack','Progress']){
        await tab(name);
        await evaluate(`Promise.all([...document.querySelectorAll('.theme-character-frame img')].map(image=>image.decode()))`);
        const layout=await evaluate(`(()=>{const headings=[...document.querySelectorAll('.page-title,.hero-title,.hero-title>span')];const safeHeadings=headings.length>0&&headings.every(e=>{const s=getComputedStyle(e);return parseFloat(s.lineHeight)/parseFloat(s.fontSize)>=1.2&&s.overflowY==='visible'&&parseFloat(s.paddingBottom)>0;});const frames=[...document.querySelectorAll('.theme-character-frame')];const overlaps=(a,b)=>a.left<b.right-1&&a.right>b.left+1&&a.top<b.bottom-1&&a.bottom>b.top+1;let artSafe=true;for(const frame of frames){const image=frame.querySelector('img'),header=frame.closest('.page-header,.hero-row');if(!image||!header||!image.complete||!image.naturalWidth||!image.src.startsWith(location.origin+'/')){artSafe=false;continue;}const imageRect=image.getBoundingClientRect();for(const control of header.querySelectorAll('button,input,select,textarea'))if(!frame.contains(control)&&overlaps(imageRect,control.getBoundingClientRect()))artSafe=false;const walker=document.createTreeWalker(header,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode;if(!node.textContent.trim()||frame.contains(node)||!node.parentElement.getClientRects().length)continue;const range=document.createRange();range.selectNodeContents(node);for(const rect of range.getClientRects())if(overlaps(imageRect,rect))artSafe=false;}}return {headings:safeHeadings,overflow:document.documentElement.scrollWidth<=innerWidth,orbs:document.querySelectorAll('.orb-drift').length,artSafe,artCount:frames.length};})()`);
        assert(layout.overflow,key+' '+name+' has no overflow at '+width);
        assert(layout.headings,key+' '+name+' title preserves descenders at '+width);
        assert.equal(layout.orbs,0,key+' '+name+' has no decorative corner orb');
        if(key==='pokemon'||key==='akatsuki'){assert(layout.artCount>0,key+' '+name+' includes bundled character artwork');assert(layout.artSafe,key+' '+name+' art loads and avoids text/controls at '+width);}
        if(key==='pokemon'||key==='akatsuki')assert.equal(await evaluate(`document.querySelectorAll('.theme-character-frame figcaption').length`),0,'No character caption boxes');
        if(key==='pokemon'&&name==='Home')assert.equal(await evaluate(`getComputedStyle(document.querySelector('.hero-row>div:first-child')).backgroundColor`),'rgba(0, 0, 0, 0)','Welcome text blends directly into sky');
        if((key==='pokemon'&&name!=='Home')||key==='akatsuki')assert(await evaluate(`getComputedStyle(document.querySelector('.page-enter>div')).backgroundImage.includes('/motifs/')`),key+' '+name+' motifs extend across the section');
      }
    }
  }
  await tab('Home');await click(`document.querySelector('button[aria-label="Change accent theme"]')`);await click(`document.querySelector('.theme-picker-grid button:has([data-theme="og"])')`);await click(button('Done'));
  assert.equal(await evaluate(`document.documentElement.dataset.identity`),'classic','Original theme skin restored');
  await evaluate(`DailySync.write=window._themeWriteOriginal;delete window._themeWriteOriginal;delete window._themeWrites;`);
  await tab('Habits');const screenshot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/private/tmp/dailyos-desktop-sync.png',Buffer.from(screenshot.data,'base64'));
  const cacheReady=await evaluate(`Promise.race([navigator.serviceWorker.ready.then(async r=>{const keys=await caches.keys();const cache=await caches.open(keys.find(k=>k.startsWith('dailyos-')));return !!await cache.match('./dailyos-sync.js');}),new Promise(resolve=>setTimeout(()=>resolve(false),8000))])`);
  assert(cacheReady,'Service worker caches the bundled sync library');
  const backupChecks=await evaluate(`(async()=>{const photosBefore=(await idbGetAll()).map(p=>[p.date,p.ts,p.blob.size]);const storedBefore=localStorage.getItem('dos_energy_v1');let confirmations=0;const confirmBefore=window.confirm;window.confirm=()=>{confirmations++;return true;};const invalid={app:'dailyos',schemaVersion:1,localStorage:{dos_energy_v1:JSON.stringify({unsafe:true})},photos:[{date:tdk(),b64:'invalid'}]};await importBackup(new File([JSON.stringify(invalid)],'invalid.json',{type:'application/json'}));const invalidUnchanged=storedBefore===localStorage.getItem('dos_energy_v1')&&JSON.stringify(photosBefore)===JSON.stringify((await idbGetAll()).map(p=>[p.date,p.ts,p.blob.size]))&&confirmations===0;const exported=await buildBackup();const safeExport=!Object.keys(exported.localStorage).some(key=>BACKUP_EXCLUDE.has(key))&&exported.photos.length===6;const write=DailySync.write,photo=DailySync.photo,timer=window.setTimeout,writes=[],photoWrites=[];DailySync.write=(key,value)=>{writes.push(key);return write(key,value);};DailySync.photo=(date,value)=>{photoWrites.push(date);return photo(date,value);};window.setTimeout=(fn,ms,...args)=>ms===600?0:timer(fn,ms,...args);try{const restored={app:'dailyos',schemaVersion:1,localStorage:{dos_energy_v1:JSON.stringify({[tdk()]:4})},photos:[exported.photos[0]]};await importBackup(new File([JSON.stringify(restored)],'valid.json',{type:'application/json'}));return {invalidUnchanged,safeExport,restored:JSON.parse(localStorage.getItem('dos_energy_v1'))[tdk()]===4,writes,photoWrites,photosRetained:(await idbGetAll()).length===6,confirmations};}finally{window.confirm=confirmBefore;DailySync.write=write;DailySync.photo=photo;window.setTimeout=timer;}})()`);
  assert(backupChecks.invalidUnchanged,'Invalid backup cannot mutate photos or local data');assert(backupChecks.safeExport,'Backup includes photos and excludes keys/sync internals');assert(backupChecks.restored&&backupChecks.photosRetained,'Valid restore updates data and retains unlisted photos');assert(backupChecks.writes.includes('dos_energy_v1')&&backupChecks.photoWrites.length===1,'Restore explicitly queues data and photo synchronization');assert.equal(backupChecks.confirmations,1,'Valid restore requires confirmation');
  assert.deepEqual(await evaluate(`window._cspEvents`),[],'No content security policy violations');
  await evaluate(`window._setTestSyncStatus(false)`);await wait(150);assert(!await evaluate(`!!document.querySelector('.app-nav,.xp-panel,.habit-list,.progress-grid')`),'Session loss hides all personal content');
  assert.deepEqual(errors,[],'No runtime exceptions');
  console.log('Passed: login privacy gate, habit/time/deletion/XP regressions, responsive photo thumbnails/cache, full-size viewer/date/arrows/Escape/outside/close, comparison and originals preserved, backup validation/export/restore/sync queue, session-loss gate, CSP and runtime checks.');
  ws.close();
  await cleanup();
})().catch(async e=>{console.error(e.message);await cleanup().catch(()=>{});process.exit(1);});
