const fs=require('node:fs'),assert=require('node:assert/strict');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const tabs=await (await fetch('http://127.0.0.1:9224/json/list')).json();
  const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
  let id=0;const pending=new Map(),errors=[];
  const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});ws.send(JSON.stringify({id:key,method,params}));});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value;};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method!=='Fetch.requestPaused')return;const {requestId,request}=m.params;const file=request.url.includes('confetti.browser.min.js')?'dailyos-confetti.min.js':request.url.includes('react-dom.production')?'dailyos-react-dom.min.js':request.url.includes('react.production')?'dailyos-react.min.js':request.url.includes('babel.min.js')?'dailyos-babel.min.js':null;if(file)send('Fetch.fulfillRequest',{requestId,responseCode:200,responseHeaders:[{name:'Content-Type',value:'application/javascript'},{name:'Access-Control-Allow-Origin',value:'*'}],body:fs.readFileSync('/private/tmp/'+file).toString('base64')});else send('Fetch.continueRequest',{requestId});});
  await send('Fetch.enable',{patterns:[{urlPattern:'*cdnjs.cloudflare.com*',requestStage:'Request'},{urlPattern:'*cdn.jsdelivr.net*',requestStage:'Request'}]});
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.clear();localStorage.setItem('dos_backup_meta_v1',JSON.stringify({lastBackup:Date.now()}));localStorage.setItem('dos_habits_v1',JSON.stringify([{id:'read',name:'Read',emoji:'📖',startTime:'09:00',endTime:'09:30'},{id:'run',name:'Run',emoji:'🏃'}]));`});
  await send('Page.navigate',{url:'http://127.0.0.1:8765/index.html'});
  for(let i=0;i<40;i++){if(await evaluate(`!!document.querySelector('.xp-panel')`))break;await wait(250);}
  assert(await evaluate(`!!document.querySelector('.xp-panel')`),'App renders without requiring an AI key: '+errors.join('\n'));
  const click=async expression=>{await evaluate(`(${expression}).click()`);await wait(150);};
  const button=label=>`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)})`;
  const tab=label=>click(`[...document.querySelectorAll('.app-nav button')].find(b=>b.textContent.trim()===${JSON.stringify(label)})`);
  const input=async(label,value)=>{await evaluate(`(()=>{const e=document.querySelector('input[aria-label=${JSON.stringify(label)}]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait(60);};
  await tab('Habits');
  const today=await evaluate('tdk()');
  const edit=async(start,end)=>{await click(`document.querySelector('button[aria-label="Edit time for Read"]')`);await input('Habit start time',start);await input('Habit end time',end);await click(button('Save habit'));};
  await edit('10:00','10:30');assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/10:00 AM/);
  await edit('11:00','11:30');assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/11:00 AM/);
  assert.equal(await evaluate(`ld('dos_habits_v1',[])[0].startTime`),'09:00','Day edit leaves base time alone');
  assert.equal(await evaluate(`ld('dos_planner_v1',{})[tdk()].habitTimes.read.start`),'11:00');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.habit-list>div')).transform`),'none','Resting row has no compositor transform');
  const nextDay=async()=>{const label=await evaluate(`new Date(shiftDateKey(tdk(),1)+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})`);if(!await evaluate(`!!document.querySelector('button[aria-label=${JSON.stringify(label)}]')`))await click(`document.querySelector('button[aria-label="Next week"]')`);await click(`document.querySelector('button[aria-label=${JSON.stringify(label)}]')`);};
  await nextDay();assert.match(await evaluate(`document.querySelector('button[aria-label="Edit time for Read"]').textContent`),/9:00 AM/);
  await click(button('Today'));await click(`document.querySelector('button[aria-label="Edit habit Read"]')`);await input('Habit start time','12:00');await input('Habit end time','12:30');await click(`document.querySelector('input[aria-label="Apply time to all days"]')`);await click(button('Save habit'));assert.equal(await evaluate(`ld('dos_habits_v1',[])[0].startTime`),'12:00');assert(!await evaluate(`ld('dos_planner_v1',{})[tdk()].habitTimes.read`));
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await click(`document.querySelector('button[aria-label="Mark Read"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),20);
  await click(`document.querySelector('button[aria-label="Remove Read"]')`);assert(await evaluate(`!!document.querySelector('[role="dialog"]')`));await click(button('Cancel'));assert(await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));
  await click(`document.querySelector('button[aria-label="Remove Read"]')`);await click(button('Delete for today only'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await nextDay();assert(await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));await click(`document.querySelector('button[aria-label="Remove Read"]')`);await click(button('Delete for all days'));assert.equal(await evaluate(`ld('dos_habits_v1',[]).some(h=>h.id==='read')`),false);await click(button('Today'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Read"]')`));
  await tab('Home');await click(`document.querySelector('button[aria-label="Bottle 1"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),5);await click(`document.querySelector('button[aria-label="Bottle 1"]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),0);
  await click(`document.querySelector('button[aria-label="Account and sync settings"]')`);assert(await evaluate(`!!document.querySelector('input[type="email"]')`));await click(`document.querySelector('[role="dialog"] button')`);
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await wait(250);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('.app-nav')).width`),'220px');assert.equal(await evaluate(`getComputedStyle(document.querySelector('.home-layout')).display`),'grid');
  assert(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),'Desktop has no horizontal overflow');
  for(const name of ['Health','Habits','Stack','Progress','Home']){await tab(name);assert(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),name+' has no desktop overflow');}
  await tab('Habits');await evaluate(`(()=>{const b=document.querySelector('button[aria-label="Reorder Run"]');b.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));})()`);
  await click(button('+ Add habit'));await input('Habit text','Stretch');await click(button('Save habit'));
  await evaluate(`document.querySelector('button[aria-label="Reorder Run"]').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))`);await wait(150);
  assert.equal(await evaluate(`document.querySelector('.habit-list button[aria-label^="Mark "]').getAttribute('aria-label')`),'Mark Stretch','Keyboard reorder moves the item');
  const points=await evaluate(`(()=>{const a=document.querySelector('button[aria-label="Reorder Run"]').getBoundingClientRect(),b=document.querySelector('button[aria-label="Reorder Stretch"]').getBoundingClientRect();return {x:a.x+a.width/2,y:a.y+a.height/2,target:b.y};})()`);
  await send('Input.dispatchMouseEvent',{type:'mousePressed',x:points.x,y:points.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:points.x,y:points.target,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:points.x,y:points.target,button:'left',clickCount:1});await wait(450);
  assert.equal(await evaluate(`document.querySelector('.habit-list button[aria-label^="Mark "]').getAttribute('aria-label')`),'Mark Run','Mouse drag reorder moves the item');
  await click(`document.querySelector('button[aria-label="Remove Stretch"]')`);await click(button('Delete for today only'));assert(!await evaluate(`!!document.querySelector('button[aria-label="Mark Stretch"]')`),'Local habit deletes for today');
  await tab('Stack');const supplement=await evaluate(`document.querySelector('button[aria-label^="Mark "]').getAttribute('aria-label')`);await click(`document.querySelector('button[aria-label=${JSON.stringify(supplement)}]')`);assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),10);
  await tab('Health');await click(`[...document.querySelectorAll('[aria-label="Day activity"] button')].find(b=>b.textContent==='Gym')`);await click(button('Mark Gym'));assert.equal(await evaluate(`ld('dos_xp_v1',{}).total`),50);
  await tab('Home');const homeShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync('/private/tmp/dailyos-home-sync.png',Buffer.from(homeShot.data,'base64'));
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert(await evaluate(`parseFloat(getComputedStyle(document.querySelector('.xp-fill')).transitionDuration)<.001`),'Reduced motion disables XP animation');
  await tab('Habits');const screenshot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/private/tmp/dailyos-desktop-sync.png',Buffer.from(screenshot.data,'base64'));
  const cacheReady=await evaluate(`Promise.race([navigator.serviceWorker.ready.then(async r=>{const keys=await caches.keys();const cache=await caches.open(keys.find(k=>k.startsWith('dailyos-')));return !!await cache.match('./dailyos-sync.js');}),new Promise(resolve=>setTimeout(()=>resolve(false),8000))])`);
  assert(cacheReady,'Service worker caches the bundled sync library');
  assert.deepEqual(errors,[],'No runtime exceptions');
  console.log('Passed: repeated instant time edits, day isolation, all-day edits, compositing removal, XP reversal, both deletion scopes/cancel, hydration XP, account form, desktop sidebar and every tab. Screenshot: /private/tmp/dailyos-desktop-sync.png');
  ws.close();
})().catch(e=>{console.error(e.message);process.exit(1);});
