const assert = require('node:assert/strict');
const {flatten,materialize,compare,eligible} = require('../dailyos-sync.js');
const xp = require('../dailyos-xp.js');
const rows = (value,stamp=1,device='phone') => Object.fromEntries(Object.entries(flatten(value,['doc'])).map(([path,value])=>[path,{path,value,stamp,device,deleted:false}]));
const merge = (a,b) => {const result={...a};Object.values(b).forEach(r=>{if(compare(r,result[r.path])>0)result[r.path]=r;});return result;};
const base={habits:[{id:'a',name:'Read',time:'09:00'},{id:'b',name:'Run'}],days:{today:{marks:{a:false},times:{a:{start:'09:00'}}}}};
assert.deepEqual(materialize(rows(base),['doc']),base);
for(const value of [{},[],{empty:[],value:null},[{id:1,name:'One'}],[{date:'2026-10-07',weight:157}]])assert.deepEqual(materialize(rows(value),['doc']),value);
const phone=rows(base), desktop=rows(base);
const name='["doc","habits","a","name"]',time='["doc","days","today","times","a","start"]';
phone[name]={...phone[name],value:{type:'value',data:'Read a book'},stamp:2};
desktop[time]={...desktop[time],value:{type:'value',data:'10:00'},stamp:3,device:'desktop'};
const combined=materialize(merge(phone,desktop),['doc']);
assert.equal(combined.habits[0].name,'Read a book');assert.equal(combined.days.today.times.a.start,'10:00');
assert.deepEqual(merge(phone,desktop),merge(desktop,phone));
const deletion={'["doc","habits","a"]':{path:'["doc","habits","a"]',deleted:true,value:null,stamp:4,device:'desktop'}};
assert.equal(materialize(merge(phone,deletion),['doc']).habits.length,1);
assert.equal(materialize(merge(merge(phone,deletion),rows(base)),['doc']).habits.length,1,'Old snapshot cannot resurrect deletion');
const tombstonePath='["doc","days","today","times","a","start"]';
assert.equal(materialize(merge(desktop,{[tombstonePath]:{path:tombstonePath,deleted:true,value:null,stamp:4,device:'phone'}}),['doc']).days.today.times.a.start,undefined);
const slot=flatten({'2026-10-07':{habitTimes:{a:{start:'10:00',end:'10:30'}}}},['dos_planner_v1']);
assert.deepEqual(slot['["dos_planner_v1","2026-10-07","habitTimes","a"]'],{type:'value',data:{start:'10:00',end:'10:30'}},'Time ranges sync atomically and cannot merge into an invalid interval');
assert.deepEqual(flatten([{id:'a',name:'Read',startTime:'10:00',endTime:'10:30'}],['dos_habits_v1'])['["dos_habits_v1","a"]'].data,{id:'a',name:'Read',startTime:'10:00',endTime:'10:30'});
assert(!eligible('dos_api_key'));assert(!eligible('dos_sync_meta_v1'));assert(!eligible('dos_xp_v1'));assert(eligible('dos_habit_checked_v1'));
const data={habits:[{id:'a',important:true}],habitChecked:{'2026-10-07':{a:true}},prayerChecked:{'2026-10-07':{Fajr:true}},suppChecked:{'2026-10-07':{s1:true}},water:{days:{'2026-10-06':2,'2026-10-07':3}},urgent:[{id:'g',completedDates:{'2026-10-07':true}}],attend:{'2026-10-07':{gym:true}}};
const total=d=>Object.values(xp.awards(d)).reduce((a,b)=>a+b,0);
assert.equal(total(data),160);
assert.deepEqual(xp.awards(data),xp.awards(data),'Duplicate evaluation does not duplicate awards');
const off={...data,habitChecked:{'2026-10-07':{a:false}}};assert.equal(total(off),130);assert.equal(total(data),160,'Rechecking only restores original XP');
assert.equal(total({...data,water:{days:{'2026-10-06':2,'2026-10-07':2}}}),155);
assert.deepEqual(xp.progress(120),{total:120,level:2,current:0,required:150});
assert.deepEqual(xp.progress(285),{total:285,level:3,current:15,required:180});
assert.equal(xp.progress(0).level,1);
const vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../index.html'),'utf8').match(/function loadHabitData\(\) \{[\s\S]*?return \{habits,planner,checked\};\n\}/)[0];
const archived={dos_habits_v1:[],dos_planner_v1:{'2026-10-07':{tasks:[{id:'deleted',title:'Old goal',done:true}],habitTasksMigrated:true,habits:[]}},dos_habit_checked_v1:{}};
const context={ld:(key,f)=>archived[key]??f,DEFAULT_HABITS:[],C:{violet:'purple'}};
vm.runInNewContext(source,context);
assert.equal(context.loadHabitData().checked['2026-10-07']?.deleted,undefined,'Deleted archived goals cannot resurrect completion or XP');
console.log('Passed: record merges, conflicts, tombstones, secrets exclusion, XP deduplication/reversal, water history and level carryover.');
